# Generated by Django 5.1.1 on 2024-09-11 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
