# Generated by Django 5.1.1 on 2024-09-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
